# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geometry_cpp_limit_skip <- function(dsn, layer, sql, ex, format, limit_n, skip_n) {
    .Call(`_dirigible_geometry_cpp_limit_skip`, dsn, layer, sql, ex, format, limit_n, skip_n)
}

geometry_cpp <- function(dsn, layer, sql, ex, fid, format) {
    .Call(`_dirigible_geometry_cpp`, dsn, layer, sql, ex, fid, format)
}

register_gdal_cpp <- function() {
    .Call(`_dirigible_register_gdal_cpp`)
}

cleanup_gdal_cpp <- function() {
    .Call(`_dirigible_cleanup_gdal_cpp`)
}

version_gdal_cpp <- function() {
    .Call(`_dirigible_version_gdal_cpp`)
}

drivers_list_gdal_cpp <- function() {
    .Call(`_dirigible_drivers_list_gdal_cpp`)
}

proj_to_wkt_gdal_cpp <- function(proj4string) {
    .Call(`_dirigible_proj_to_wkt_gdal_cpp`, proj4string)
}

driver_gdal_cpp <- function(dsn) {
    .Call(`_dirigible_driver_gdal_cpp`, dsn)
}

layer_names_gdal_cpp <- function(dsn) {
    .Call(`_dirigible_layer_names_gdal_cpp`, dsn)
}

feature_count_gdal_cpp <- function(dsn, layer, sql, ex) {
    .Call(`_dirigible_feature_count_gdal_cpp`, dsn, layer, sql, ex)
}

read_fields_gdal_cpp <- function(dsn, layer, sql, limit_n, skip_n, ex, fid_column_name) {
    .Call(`_dirigible_read_fields_gdal_cpp`, dsn, layer, sql, limit_n, skip_n, ex, fid_column_name)
}

read_geometry_gdal_cpp <- function(dsn, layer, sql, what, textformat, limit_n, skip_n, ex) {
    .Call(`_dirigible_read_geometry_gdal_cpp`, dsn, layer, sql, what, textformat, limit_n, skip_n, ex)
}

read_names_gdal_cpp <- function(dsn, layer, sql, limit_n, skip_n, ex) {
    .Call(`_dirigible_read_names_gdal_cpp`, dsn, layer, sql, limit_n, skip_n, ex)
}

projection_info_gdal_cpp <- function(dsn, layer, sql) {
    .Call(`_dirigible_projection_info_gdal_cpp`, dsn, layer, sql)
}

report_fields_gdal_cpp <- function(dsn, layer, sql) {
    .Call(`_dirigible_report_fields_gdal_cpp`, dsn, layer, sql)
}

vsi_list_gdal_cpp <- function(dsn) {
    .Call(`_dirigible_vsi_list_gdal_cpp`, dsn)
}

sds_list_gdal_cpp <- function(dsn) {
    .Call(`_dirigible_sds_list_gdal_cpp`, dsn)
}

warp_in_memory_gdal_cpp <- function(dsn, source_WKT, target_WKT, target_geotransform, target_dim, band) {
    .Call(`_dirigible_warp_in_memory_gdal_cpp`, dsn, source_WKT, target_WKT, target_geotransform, target_dim, band)
}

raster_info_gdal_cpp <- function(dsn, min_max) {
    .Call(`_dirigible_raster_info_gdal_cpp`, dsn, min_max)
}

raster_gcp_gdal_cpp <- function(dsn) {
    .Call(`_dirigible_raster_gcp_gdal_cpp`, dsn)
}

raster_io_gdal_cpp <- function(dsn, window, band, resample) {
    .Call(`_dirigible_raster_io_gdal_cpp`, dsn, window, band, resample)
}

gdal_read_fids_all <- function(dsn, layer, sql, ex) {
    .Call(`_dirigible_gdal_read_fids_all`, dsn, layer, sql, ex)
}

gdal_read_fids_ij <- function(dsn, layer, sql, ex, ij) {
    .Call(`_dirigible_gdal_read_fids_ij`, dsn, layer, sql, ex, ij)
}

gdal_read_fids_ia <- function(dsn, layer, sql, ex, ia) {
    .Call(`_dirigible_gdal_read_fids_ia`, dsn, layer, sql, ex, ia)
}

gdal_dsn_read_geom_all <- function(dsn, layer, sql, ex, format) {
    .Call(`_dirigible_gdal_dsn_read_geom_all`, dsn, layer, sql, ex, format)
}

gdal_dsn_read_geom_ij <- function(dsn, layer, sql, ex, format, ij) {
    .Call(`_dirigible_gdal_dsn_read_geom_ij`, dsn, layer, sql, ex, format, ij)
}

gdal_dsn_read_geom_ia <- function(dsn, layer, sql, ex, format, ia) {
    .Call(`_dirigible_gdal_dsn_read_geom_ia`, dsn, layer, sql, ex, format, ia)
}

