# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

register_gdal <- function() {
    .Call(`_dirigible_register_gdal`)
}

cleanup_gdal <- function() {
    .Call(`_dirigible_cleanup_gdal`)
}

driver_gdal <- function(dsn) {
    .Call(`_dirigible_driver_gdal`, dsn)
}

layer_names_gdal <- function(dsn) {
    .Call(`_dirigible_layer_names_gdal`, dsn)
}

feature_count_gdal <- function(dsn, layer, iterate) {
    .Call(`_dirigible_feature_count_gdal`, dsn, layer, iterate)
}

read_fields_gdal <- function(dsource, layer, sql, limit_n, skip_n, ex, fid_column_name) {
    .Call(`_dirigible_read_fields_gdal`, dsource, layer, sql, limit_n, skip_n, ex, fid_column_name)
}

